ssf_version: 0.0.1

application:
  id: Whisper-tiny
  name: Whisper API
  desc: A very simple API for whisper
  version: 1.0
  module: app.py
  ipus: 2
  trace: True
  artifacts: []

  dependencies:
    python: optimum-graphcore==0.6, librosa, tokenizers==0.12.1

  package:
    inclusions: []
    exclusions: []
    tag: "deployment-test:latest"
    docker:
        baseimage: "graphcore/pytorch:latest"

endpoints:

  - id: whisper_transcription
    version: 1
    desc: Audio to text using Whisper tiny
    custom: ~

    inputs:

      - id: audio_file
        type: TempFile
        desc: The audio file
        
    outputs:

      - id: result
        type: String
        desc: Transcript
