_examples_internal_repository: &_examples_internal_repository
  origin: examples-internal/
  ref: null


_common_target_repository: &_common_target_repository
    origin: notebooks/
    ref: null


flan-t5:
  source:
    paths:
    - expression: '*'
      path: nlp/t5/popxl
      recursive: true
    excludes:
    - path: nlp/t5/popxl/pytest.ini
    - path: nlp/t5/popxl/.ci
    - path: nlp/t5/popxl/README.md
    - path: nlp/t5/popxl/.gitignore
    - path: nlp/t5/popxl/tests
    repository:
      <<: *_examples_internal_repository
      prefix: nlp/t5/popxl
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: natural-language-processing/doing-more-with-flan-t5/
