
_optimum_graphcore_repository: &_optimum_graphcore_repository
  origin: https://github.com/huggingface/optimum-graphcore.git
  ref: main

_examples_internal_repository: &_examples_internal_repository
  origin: examples-internal/
  ref: null


_common_target_repository: &_common_target_repository
    origin: notebooks/
    ref: null

whisper_quantized:
  source:
    paths:
    - expression: '*'
      path: notebooks/whisper-quantized-example.ipynb
      recursive: true
    repository:
      <<: *_optimum_graphcore_repository
      prefix: notebooks/
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: whisper/

natural-language-processing-main:
  source:
    paths:
    - path: notebooks/text_summarization.ipynb
    repository:
      <<: *_optimum_graphcore_repository
      prefix: notebooks/
  target:
    renames: {natural-language-processing/text_summarization.ipynb: natural-language-processing/text_summarization_inference.ipynb}
    repository:
      <<: *_common_target_repository
      prefix:  natural-language-processing/

text_embeddings_models:
  source:
    paths:
    - expression: '*'
      path: notebooks/text_embeddings_models
      recursive: true
    repository:
      <<: *_optimum_graphcore_repository
      prefix: notebooks/
  target:
    renames: {natural-language-processing/text_embeddings_models: natural-language-processing/text-embeddings-models}
    repository:
      <<: *_common_target_repository
      prefix: natural-language-processing/
