
_optimum_graphcore_repository: &_optimum_graphcore_repository
  origin: https://github.com/huggingface/optimum-graphcore.git
  ref: main

_examples_internal_repository: &_examples_internal_repository
  origin: examples-internal/
  ref: sdk-release-3.4


_common_target_repository: &_common_target_repository
  origin: notebooks/
  ref: null


natural-language-processing-main:
  source:
    paths:
    - path: notebooks/flan_t5_inference.ipynb
    - path: notebooks/introduction_to_optimum_graphcore.ipynb
    - path: notebooks/name-entity-extraction.ipynb
    - path: notebooks/sentiment_analysis.ipynb
    - path: notebooks/squad_preprocessing.py
    - path: notebooks/text_summarization.ipynb
    - path: notebooks/translation.ipynb
    repository:
      <<: *_optimum_graphcore_repository
      prefix: notebooks/
  target:
    renames: {natural-language-processing/flan_t5_inference.ipynb: natural-language-processing/Flan-T5-generative-inference.ipynb,
              natural-language-processing/text_summarization.ipynb: natural-language-processing/text_summarization_BART_L_inference.ipynb}
    repository:
      <<: *_common_target_repository
      prefix:  natural-language-processing/

natural-language-processing-extra:
  source:
    paths:
    - path: notebooks/deberta-blog-notebook.ipynb
    - path: notebooks/external_model.ipynb
    - path: notebooks/language_modelling_from_scratch.ipynb
    - path: notebooks/mt5_translation.ipynb
    - path: notebooks/mt5_xnli.ipynb
    - path: notebooks/multiple_choice.ipynb
    - path: notebooks/question_answering.ipynb
    - path: notebooks/summarization.ipynb
    - path: notebooks/text_classification.ipynb
    - path: notebooks/token_classification.ipynb
    repository:
      <<: *_optimum_graphcore_repository
      prefix: notebooks/
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix:  natural-language-processing/other-use-cases/

text_embeddings_models:
  source:
    paths:
    - expression: '*'
      path: notebooks/text_embeddings_models/config.py
      path: notebooks/text_embeddings_models/text-embeddings-on-ipu.ipynb
      recursive: true
    repository:
      <<: *_optimum_graphcore_repository
      prefix: notebooks/text_embeddings_models/
  target:
    repository:
      <<: *_common_target_repository
      prefix: natural-language-processing/text-embeddings-models/

managing_ipu_resources:
  source:
    paths:
    - path: notebooks/managing_ipu_resources.ipynb
    repository:
      <<: *_optimum_graphcore_repository
      prefix: notebooks/
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: useful-tips/

stable-diffusion:
  source:
    paths:
    - expression: '*'
      path: notebooks/stable_diffusion
      recursive: true
    excludes:
    - expression: '*'
      path: notebooks/stable_diffusion/stable_diffusion_space
      recursive: true
    repository:
      <<: *_optimum_graphcore_repository
      prefix: notebooks/stable_diffusion
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: stable-diffusion/

image-classification:
  source:
    paths:
    - path: notebooks/image_classification.ipynb
    repository:
      <<: *_optimum_graphcore_repository
      prefix: notebooks
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: image-classification/

# Disable deploying this notebook as we are having trouble uploading the
# dataset to Paperspace. We have removed this notebook from the HF runtime repo
# until that is resolved.
# The notebook is also silently failing non-deterministically, so the don't deploy
# until that's resolved.
# audio-classification:
#   source:
#     paths:
#     - path: notebooks/audio_classification.ipynb
#     repository:
#       <<: *_optimum_graphcore_repository
#       prefix: notebooks/
#   target:
#     renames: {}
#     repository:
#       <<: *_common_target_repository
#       prefix: audio-processing/

wav2vec2:
  source:
    paths:
    - path: notebooks/wav2vec2/requirements.txt
    - path: notebooks/wav2vec2/wav2vec2-fine-tuning-checkpoint.ipynb
    - path: notebooks/wav2vec2/wav2vec2-inference-checkpoint.ipynb
    repository:
      <<: *_optimum_graphcore_repository
      prefix: notebooks/wav2vec2/
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: audio-processing/

gptj:
  source:
    paths:
    - expression: '*'
      path: nlp/gpt_j/popxl
      recursive: true
    excludes:
    - path: nlp/gpt_j/popxl/README.md
    - path: nlp/gpt_j/popxl/.gitignore
    - expression: '*'
      path: nlp/gpt_j/popxl/.ci
      recursive: true
    repository:
      <<: *_examples_internal_repository
      prefix: nlp/gpt_j/popxl
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: gptj-text-generation

packed-bert:
  source:
    paths:
    - expression: '*'
      path: notebooks/packed_bert
      recursive: true
    repository:
      <<: *_optimum_graphcore_repository
      prefix: notebooks/packed_bert
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: packed-bert/

whisper:
  source:
    paths:
    - path: notebooks/whisper-example.ipynb
    - path: notebooks/whisper-quantized-example.ipynb
    - path: notebooks/whisper_finetuning.ipynb
    repository:
      <<: *_optimum_graphcore_repository
      prefix: notebooks/
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: whisper/

dolly2:
  source:
    paths:
    - expression: '*'
      path: nlp/dolly/popxl
      recursive: true
    excludes:
    - path: nlp/dolly/popxl/README.md
    - path: nlp/dolly/popxl/.ci
    - path: nlp/dolly/popxl/pytest.ini
    - path: nlp/dolly/popxl/run-inference.py
    - path: nlp/dolly/popxl/.gitignore
    repository:
      <<: *_examples_internal_repository
      prefix: nlp/dolly/popxl
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: dolly2-instruction-following/

llama2:
  source:
    paths:
    - expression: '*'
      path: nlp/llama/popxl
      recursive: true
    excludes:
    - path: nlp/llama/popxl/pytest.ini
    - path: nlp/llama/popxl/run-inference.py
    - path: nlp/llama/popxl/.gitignore
    repository:
      <<: *_examples_internal_repository
      prefix: nlp/llama/popxl
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: llama2-chatbot/


magma:
  source:
    paths:
    - expression: '*'
      path: multimodal/magma/popxl
      recursive: true
    excludes:
    - path: multimodal/magma/popxl/pytest.ini
    - path: multimodal/magma/popxl/.ci
    - path: multimodal/magma/popxl/README.md
    - path: multimodal/magma/popxl/.gitignore
    - path: multimodal/magma/popxl/tests
    repository:
      <<: *_examples_internal_repository
      prefix: multimodal/magma/popxl/
  target:
    renames: {multimodal/magma/magma_interactive.ipynb: multimodal/magma/Image-description-using-MAGMA.ipynb}
    repository:
      <<: *_common_target_repository
      prefix: multimodal/magma


flan-t5:
  source:
    paths:
    - expression: '*'
      path: nlp/t5/popxl
      recursive: true
    excludes:
    - path: nlp/t5/popxl/pytest.ini
    - path: nlp/t5/popxl/.ci
    - path: nlp/t5/popxl/README.md
    - path: nlp/t5/popxl/.gitignore
    - path: nlp/t5/popxl/tests
    repository:
      <<: *_examples_internal_repository
      prefix: nlp/t5/popxl
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: natural-language-processing/doing-more-with-flan-t5/
