
_optimum_graphcore_repository: &_optimum_graphcore_repository
  origin: https://github.com/huggingface/optimum-graphcore.git
  ref: main

_examples_internal_repository: &_examples_internal_repository
  origin: examples-internal/
  ref: null


_common_target_repository: &_common_target_repository
    origin: notebooks/
    ref: null

gptj:
  source:
    paths:
    - path: nlp/gpt_j/popxl/GPTJ-generative-inference.ipynb
    - path: nlp/gpt_j/popxl/config/inference.yml
    excludes:
    - path: nlp/gpt_j/popxl/README.md
    - path: nlp/gpt_j/popxl/.gitignore
    - path: nlp/gpt_j/popxl/.ci
    repository:
      <<: *_examples_internal_repository
      prefix: nlp/gpt_j/popxl
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: gptj-text-generation
