name: 2. Tests on Local vPOD

on:
  workflow_dispatch:
    inputs:
      test_env:
        type: choice
        description: "Testing environment"
        required: false
        default: 'Local'
        options:
        - Local
        - Paperspace
      docker_image:
        type: string
        description: "Docker image used in notebook testing"
        required: false
        default: "graphcore/pytorch-jupyter:3.2.1-ubuntu-20.04-20230531"
      notebooks:
        type: string
        description: "List of notebooks to test in JSON format"
        required: false
        default: '["Graphcore-HuggingFace-README_first"]'
      machine_types:
        type: string
        description: "List of machines types"
        required: false
        default: '["IPU-POD4"]'
      test_mode:
        type: string
        description: "The test workload that we are running, default or config set in the .github/test_configs/image-config.yaml"
        required: false
      test_config:
        type: string
        description: "Config which can be used to define special parameters such as docker image."
        default: ".github/test_configs/image-config.yaml"
        required: false

  pull_request:
    branches-ignore:
      - 'gh-action-branches/**'
  schedule:
    # run at 7:00 PM GMT every night
    - cron:  '0 19 * * TUE,FRI'


jobs:
  tests:
    uses: graphcore/paperspace-automation/.github/workflows/subwf-vpod-tests-for-nb-repo.yml@main
    with:
      docker_image: ${{ inputs.docker_image || 'graphcore/pytorch-jupyter:3.2.1-ubuntu-20.04-20230531' }}
      notebooks: ${{ inputs.notebooks }}
      machine_types: ${{ inputs.machine_types }}
      test_env: ${{ inputs.test_env || 'Local' }}
      test_mode: "default"
      test_config: ${{ inputs.test_config || '.github/test_configs/image-config.yaml' }}
    secrets:
      gh_token:  ${{ secrets.GH_TOKEN_SYNC_REPOS }}
      hugging_face_hub_token: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
      slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
      ci_slack_channel_id: ${{ secrets.CI_SLACK_CHANNEL_ID }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  tests-early-access:
    uses: graphcore/paperspace-automation/.github/workflows/subwf-vpod-tests-for-nb-repo.yml@main
    with:
      docker_image: ${{ inputs.docker_image || 'graphcore/pytorch-paperspace-early-access:3.3.0-EA.1-ubuntu-20.04-20230504' }}
      notebooks: ${{ inputs.notebooks }}
      machine_types: ${{ inputs.machine_types }}
      test_env: ${{ inputs.test_env || 'Local' }}
      test_mode: "early-access-tests"
      test_config: ${{ inputs.test_config || '.github/test_configs/image-config.yaml' }}
    secrets:
      gh_token:  ${{ secrets.GH_TOKEN_SYNC_REPOS }}
      hugging_face_hub_token: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
      slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
      ci_slack_channel_id: ${{ secrets.CI_SLACK_CHANNEL_ID }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
