name: 3. Probe on PS env

on:
  workflow_dispatch:
    inputs:
      docker_image:
        type: string
        description: "Docker image used in notebook testing"
        required: false
        default: "graphcore/pytorch-paperspace:3.3.0-ubuntu-20.04-20230703"
  pull_request:
  schedule:
    # run every 6h and at 9am
    - cron:  '05 0,6,9,12,18 * * *'


jobs:
  probe-in-ps:
    name: Probe in PS env
    uses: graphcore/paperspace-automation/.github/workflows/subwf-probe-in-ps.yml@main
    with:
      docker_image: ${{ inputs.docker_image || 'graphcore/pytorch-paperspace:3.3.0-ubuntu-20.04-20230703' }}
    secrets:
      gh_user: ${{ secrets.GH_TOKEN_USER }}
      gh_token:  ${{ secrets.GH_TOKEN_SYNC_REPOS }}
      paperspace_api_key: ${{ secrets.PAPERSPACE_API_KEY }}
      gradient_ui_email: ${{ secrets.GRADIENT_UI_EMAIL }}
      gradient_ui_password: ${{ secrets.GRADIENT_UI_PASSWORD }}
      gradient_validation_key: ${{ secrets.GRADIENT_VALIDATION_KEY }}
      slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
      ci_slack_channel_id: ${{ secrets.CI_SLACK_CHANNEL_ID }}
